version: "3.8"
services:
  react:
    build:
      context: ./
      dockerfile: ./docker/react/Dockerfile
    command: sh -c 'npm run start'
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - "./react:/react"
    working_dir: /react
