version: "3.8"
services:
  react:
    build:
      context: ./
      dockerfile: ./react/Dockerfile
    command: sh -c 'npm run start'
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - "./react:/react"
    working_dir: /react
  next:
    build:
      context: ./
      dockerfile: ./next/Dockerfile
    command: sh -c 'npm run dev'
    ports:
      - "3001:3001"
    tty: true
    volumes:
      - "./next:/next"
    working_dir: /next
  typescript:
    build:
      context: ./
      dockerfile: ./typescript/app/Dockerfile
    command: sh -c 'node'
    ports:
      - "3002:3002"
    tty: true
    volumes:
      - "./typescript/app:/usr/src/app"
    working_dir: /usr/src/app
